class_name _PovDirectionsWidget extends Control

@onready var pov_image_rect: TextureRect = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/PovImageRect
@onready var pov_button: Button = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/MarginContainer/VBoxContainer/PovButton
@onready var top_pov_name: LineEdit = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/MarginContainer/VBoxContainer/DirectionsContainer/TopPovName
@onready var left_pov_name: LineEdit = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/MarginContainer/VBoxContainer/DirectionsContainer/LeftPovName
@onready var right_pov_name: LineEdit = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/MarginContainer/VBoxContainer/DirectionsContainer/RightPovName
@onready var bottom_pov_name: LineEdit = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/MarginContainer/VBoxContainer/DirectionsContainer/BottomPovName
@onready var rotation_slider: HSlider = $VBoxContainer/VBoxContainer/RotationSlider
@onready var arrow_widget: _ArrowWidget = $VBoxContainer/ArrowWidget
@onready var properies_container: VBoxContainer = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/MarginContainer/VBoxContainer

const NO_IMAGE_POV = preload("uid://dwj11t2nw18l2")
const POV_WIDGET = preload("uid://c6s6iskf8pk6k")

var pov : Pov = Pov.new()
var coords : Vector2
var _is_dragging: bool = false
var _drag_offset: Vector2 = Vector2.ZERO
var _is_toggling_properties: bool = false
@export var colapse_speed : float = 0.2

signal changed

func _ready() -> void:
	# Generated by GitHub Copilot (GPT-5.3-Codex): arrow-only drag interaction hook.
	arrow_widget.mouse_filter = Control.MOUSE_FILTER_STOP
	arrow_widget.gui_input.connect(_on_arrow_widget_gui_input)

func parse_pov_directions() -> PovDirections:
	var p_dir := PovDirections.new()
	p_dir.pov = pov
	p_dir.left = left_pov_name.text
	p_dir.top = top_pov_name.text
	p_dir.right = right_pov_name.text
	p_dir.bottom = bottom_pov_name.text
	p_dir.coords = coords
	p_dir.rotation = rotation_slider.value
	changed.emit()
	return p_dir

func load_pov_directions(p_dir : PovDirections) -> void:
	load_pov(p_dir.pov)
	if p_dir.left:
		left_pov_name.text = p_dir.left
	if p_dir.top:
		top_pov_name.text = p_dir.top
	if p_dir.right:
		right_pov_name.text = p_dir.right
	if p_dir.bottom:
		bottom_pov_name.text = p_dir.bottom
	rotation_slider.value = p_dir.rotation
	await get_tree().process_frame
	spin_arrow(p_dir.rotation)
	coords = p_dir.coords

func load_pov(new_pov: Pov) -> void:
	pov = new_pov
	if new_pov.image:
		pov_image_rect.texture = new_pov.image
	else:
		pov_image_rect.texture = NO_IMAGE_POV
	if new_pov.name:
		pov_button.text = new_pov.name
	else:
		pov_button.text = "Pov"

## 0 to 1
func spin_arrow(value: float) -> void:
	arrow_widget.rotation_degrees = 360*value

func open_pov_widget() -> void:
	var pw : _PovWidget = POV_WIDGET.instantiate()
	var p : Control = get_tree().get_first_node_in_group("util_parent_control")
	if (p == null):
		p = self
	p.add_child(pw)
	pw.load_pov(pov)
	pw.closed.connect(load_pov)

func _on_pov_button_pressed() -> void:
	open_pov_widget()

func _on_pov_image_rect_gui_input(event: InputEvent) -> void:
	if Input.is_action_just_pressed("ui_mouse_pressed"):
		_toggle_properties_preserve_arrow_position()

func _arrow_center_in_parent_local() -> Vector2:
	var parent_ci := get_parent() as CanvasItem
	if parent_ci == null:
		return Vector2.ZERO
	var center_local := arrow_widget.size * 0.5
	var center_canvas := arrow_widget.get_global_transform_with_canvas() * center_local
	return parent_ci.get_global_transform_with_canvas().affine_inverse() * center_canvas

func _toggle_properties_preserve_arrow_position() -> void:
	if _is_toggling_properties:
		return
	_is_toggling_properties = true

	var old_arrow_center := _arrow_center_in_parent_local()
	var old_arrow_rotation := arrow_widget.rotation
	properies_container.visible = !properies_container.visible
	await get_tree().process_frame
	arrow_widget.rotation = old_arrow_rotation
	position += old_arrow_center - _arrow_center_in_parent_local()
	# One more settle pass keeps it stable across late container updates.
	await get_tree().process_frame
	arrow_widget.rotation = old_arrow_rotation
	position += old_arrow_center - _arrow_center_in_parent_local()
	spin_arrow(rotation_slider.value)

	_is_toggling_properties = false

signal moving
func _on_arrow_widget_gui_input(event: InputEvent) -> void:
	# Generated by GitHub Copilot (GPT-5.3-Codex): drag widget by the arrow handle.
	if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT:
		if event.pressed:
			_is_dragging = true
			_drag_offset = position - _parent_local_mouse_pos()
			accept_event()
		else:
			_is_dragging = false
			accept_event()

	if event is InputEventMouseMotion and _is_dragging:
		position = _parent_local_mouse_pos() + _drag_offset
		_update_coords_from_position()
		accept_event()
		moving.emit()

func _parent_local_mouse_pos() -> Vector2:
	var parent_ci := get_parent() as CanvasItem
	if parent_ci == null:
		return Vector2.ZERO
	var mouse_canvas := get_viewport().get_mouse_position()
	return parent_ci.get_global_transform_with_canvas().affine_inverse() * mouse_canvas

func _update_coords_from_position() -> void:
	coords = position + Vector2(size.x * 0.5, size.y * 0.875)

signal closed
func _on_close_button_pressed() -> void:
	closed.emit()
	await  get_tree().process_frame
	changed.emit()
	queue_free()

func _on_h_slider_value_changed(value: float) -> void:
	spin_arrow(value)
	changed.emit()
func _on_pov_image_rect_item_rect_changed() -> void:
	changed.emit()
func _on_top_pov_name_text_changed(new_text: String) -> void:
	changed.emit()
func _on_left_pov_name_text_changed(new_text: String) -> void:
	changed.emit()
func _on_right_pov_name_text_changed(new_text: String) -> void:
	changed.emit()
func _on_bottom_pov_name_text_changed(new_text: String) -> void:
	changed.emit()
