class_name _PovDirectionsWidget extends Control

@onready var pov_button: Button = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/MarginContainer/VBoxContainer/PovButton
@onready var top_pov_name_widget: _PovNameWidget = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/MarginContainer/VBoxContainer/DirectionsContainer/TopPovNameWidget
@onready var left_pov_name_widget: _PovNameWidget = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/MarginContainer/VBoxContainer/DirectionsContainer/LeftPovNameWidget
@onready var right_pov_name_widget: _PovNameWidget = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/MarginContainer/VBoxContainer/DirectionsContainer/RightPovNameWidget
@onready var bottom_pov_name_widget: _PovNameWidget = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/MarginContainer/VBoxContainer/DirectionsContainer/BottomPovNameWidget
@onready var rotation_slider: HSlider = $VBoxContainer/VBoxContainer/RotationSlider
@onready var pov_image_rect: TextureRect = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/PovImageRect
@onready var arrow_widget: _ArrowWidget = $VBoxContainer/ArrowWidget
@onready var properies_container: VBoxContainer = $VBoxContainer/VBoxContainer/VBoxContainer/Panel/VBoxContainer/MarginContainer/VBoxContainer
@onready var pov_directions_stack_widget: _PovDirectionsStackWidget = $VBoxContainer/VBoxContainer/VBoxContainer/PovDirectionsStackWidget

const NO_IMAGE_POV = preload("uid://dwj11t2nw18l2")
const POV_WIDGET = preload("uid://c6s6iskf8pk6k")

var pov : Pov = Pov.new()
var coords : Vector2
var _arrow_rot : float = 0
var _is_dragging: bool = false
var _drag_offset: Vector2 = Vector2.ZERO
@export var arrow_speed : float = 30

signal changed
signal clone_requested(clicked_pov: Pov)

func _ready() -> void:
	# Generated by GitHub Copilot (GPT-5.3-Codex): arrow-only drag interaction hook.
	arrow_widget.mouse_filter = Control.MOUSE_FILTER_STOP
	pov_directions_stack_widget.pov_dir_widget = self
	if !pov_directions_stack_widget.changed.is_connected(_on_stack_widget_changed):
		pov_directions_stack_widget.changed.connect(_on_stack_widget_changed)
	if !pov_directions_stack_widget.clone_requested.is_connected(_on_stack_clone_requested):
		pov_directions_stack_widget.clone_requested.connect(_on_stack_clone_requested)

func _physics_process(delta: float) -> void:
	# Smoothly animate arrow rotation to match the slider.
	_arrow_rot = lerpf(_arrow_rot, rotation_slider.value, arrow_speed*delta)
	spin_arrow(_arrow_rot)

func parse_pov_directions() -> PovDirections:
	# Serialize the widget state into a PovDirections resource.
	var p_dir := PovDirections.new()
	p_dir.pov = pov
	p_dir.left = left_pov_name_widget.get_pov_name()
	p_dir.top = top_pov_name_widget.get_pov_name()
	p_dir.right = right_pov_name_widget.get_pov_name()
	p_dir.bottom = bottom_pov_name_widget.get_pov_name()
	p_dir.coords = coords
	p_dir.rotation = rotation_slider.value
	return p_dir

func save_pov_directions_file(path: String) -> void:
	ResourceSaver.save(parse_pov_directions(), path)

func load_pov_directions(p_dir : PovDirections) -> void:
	load_pov(p_dir.pov)
	if p_dir.left:
		left_pov_name_widget.load_pov_name(p_dir.left)
	if p_dir.top:
		top_pov_name_widget.load_pov_name(p_dir.top)
	if p_dir.right:
		right_pov_name_widget.load_pov_name(p_dir.right)
	if p_dir.bottom:
		bottom_pov_name_widget.load_pov_name(p_dir.bottom)
	rotation_slider.value = p_dir.rotation
	coords = p_dir.coords
	update_widget()

func load_pov(new_pov: Pov) -> void:
	# Update the widget visuals and button title from a Pov resource.
	pov = new_pov
	if new_pov.images and new_pov.images[0].texture:
		pov_image_rect.texture = new_pov.images[0].texture
	else:
		pov_image_rect.texture = NO_IMAGE_POV
	if new_pov.name:
		pov_button.text = new_pov.name
	else:
		pov_button.text = "Pov"
	changed.emit()

## 0 to 1
func spin_arrow(value: float) -> void:
	arrow_widget.rotation_degrees = 360*value

func open_pov_widget() -> void:
	# Open the POV editor window for this entry.
	var pw : _PovWidget = POV_WIDGET.instantiate()
	var p : Control = get_tree().get_first_node_in_group("util_parent_control")
	if (p == null):
		p = self
	p.add_child(pw)
	pw.load_pov(pov)
	pw.closed.connect(load_pov)

func _on_pov_button_pressed() -> void:
	open_pov_widget()

func _on_pov_image_rect_gui_input(event: InputEvent) -> void:
	if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_RIGHT and event.pressed:
		clone_requested.emit(pov)
		accept_event()
		return
	if Input.is_action_just_pressed("ui_mouse_pressed"):
		_toggle_properties()

func _on_upper_panel_gui_input(event: InputEvent) -> void:
	if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_RIGHT and event.pressed:
		clone_requested.emit(pov)
		accept_event()

func _on_gui_input(event: InputEvent) -> void:
	pass

func _on_stack_clone_requested(clicked_pov: Pov) -> void:
	clone_requested.emit(clicked_pov)

func _arrow_center_in_parent_local() -> Vector2:
	var parent_ci := get_parent() as CanvasItem
	if parent_ci == null:
		return Vector2.ZERO
	var center_local := arrow_widget.size * 0.5
	var center_canvas := arrow_widget.get_global_transform_with_canvas() * center_local
	return parent_ci.get_global_transform_with_canvas().affine_inverse() * center_canvas

func _toggle_properties() -> void:
	properies_container.visible = !properies_container.visible
	pov_directions_stack_widget.visible = properies_container.visible
	update_widget()


signal moving
func _on_arrow_widget_gui_input(event: InputEvent) -> void:
	# Generated by GitHub Copilot (GPT-5.3-Codex): drag widget by the arrow handle.
	if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT:
		if event.pressed:
			_is_dragging = true
			_drag_offset = position - _parent_local_mouse_pos()
			accept_event()
		else:
			_is_dragging = false
			accept_event()

	if event is InputEventMouseMotion and _is_dragging:
		position = _parent_local_mouse_pos() + _drag_offset
		_update_coords_from_position()
		accept_event()
		moving.emit()

func _parent_local_mouse_pos() -> Vector2:
	var parent_ci := get_parent() as CanvasItem
	if parent_ci == null:
		return Vector2.ZERO
	var mouse_canvas := get_viewport().get_mouse_position()
	return parent_ci.get_global_transform_with_canvas().affine_inverse() * mouse_canvas

func _update_coords_from_position() -> void:
	coords = _arrow_center_in_parent_local()

func update_position_from_coords() -> void:
	position += coords - _arrow_center_in_parent_local()

func update_widget() -> void:
	await get_tree().process_frame
	update_position_from_coords()
	changed.emit()

signal closed
func _on_close_button_pressed() -> void:
	closed.emit()
	update_widget()
	queue_free()

func _on_h_slider_value_changed(value: float) -> void:
	update_widget()
func _on_pov_image_rect_item_rect_changed() -> void:
	pass#update_widget()
func _on_top_pov_name_text_changed(new_text: String) -> void:
	update_widget()
func _on_left_pov_name_text_changed(new_text: String) -> void:
	update_widget()
func _on_right_pov_name_text_changed(new_text: String) -> void:
	update_widget()
func _on_bottom_pov_name_text_changed(new_text: String) -> void:
	update_widget()
func _on_pov_directions_stack_widget_changed() -> void:
	update_widget()
func _on_stack_widget_changed() -> void:
	update_widget()
