class_name _PuzzlePovDirectionsWidget extends Control

@export var pov_button: Button
@export var back_pov_name_widget: _PovNameWidget
@export var pov_image_rect: TextureRect
@export var circle_widget: Control
@export var properies_container: Container

const PUZZLE_POV_WIDGET = preload("uid://ckx7ly58wwqe4")
const NO_IMAGE_POV = preload("uid://dwj11t2nw18l2")

var puzzle_pov : PuzzlePov = PuzzlePov.new()
var coords : Vector2
var _is_dragging: bool = false
var _drag_offset: Vector2 = Vector2.ZERO

signal changed
signal clone_requested(clicked_pov: PuzzlePov)

func _ready() -> void:
	circle_widget.mouse_filter = Control.MOUSE_FILTER_STOP

func _physics_process(delta: float) -> void:
	pass

func parse_puzzle_pov() -> PuzzlePov:
	# Serialize the widget state into a PovDirections resource.
	puzzle_pov.coords = coords
	puzzle_pov.back_pov = back_pov_name_widget.get_pov_name()
	return puzzle_pov

func save_puzzle_pov_file(path: String) -> void:
	ResourceSaver.save(parse_puzzle_pov(), path)

func load_puzzle_pov(new_pov: PuzzlePov) -> void:
	# Update the widget visuals and button title from a Pov resource.
	puzzle_pov = new_pov
	if puzzle_pov.images and puzzle_pov.images[0].texture:
		pov_image_rect.texture = puzzle_pov.images[0].texture
	else:
		pov_image_rect.texture = NO_IMAGE_POV
	if puzzle_pov.name:
		pov_button.text = puzzle_pov.name
	else:
		pov_button.text = "Puzzle Pov"
	if puzzle_pov.back_pov:
		back_pov_name_widget.load_pov_name(puzzle_pov.back_pov)
	coords = puzzle_pov.coords
	changed.emit()
	update_widget()

func open_puzzle_pov_widget() -> void:
	# Open the POV editor window for this entry.
	var ppw : _PuzzlePovWidget = PUZZLE_POV_WIDGET.instantiate()
	var p : Control = get_tree().get_first_node_in_group("util_parent_control")
	if (p == null):
		p = self
	p.add_child(ppw)
	ppw.load_puzzle_pov(puzzle_pov)
	ppw.closed.connect(load_puzzle_pov)

func _on_pov_button_pressed() -> void:
	open_puzzle_pov_widget()

func _on_pov_image_rect_gui_input(event: InputEvent) -> void:
	if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_RIGHT and event.pressed:
		clone_requested.emit(puzzle_pov)
		accept_event()
		return
	if Input.is_action_just_pressed("ui_mouse_pressed"):
		_toggle_properties()

func _on_upper_panel_gui_input(event: InputEvent) -> void:
	if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_RIGHT and event.pressed:
		clone_requested.emit(puzzle_pov)
		accept_event()

func _on_gui_input(event: InputEvent) -> void:
	pass

func _on_stack_clone_requested(clicked_pov: Pov) -> void:
	clone_requested.emit(clicked_pov)

func _circle_center_in_parent_local() -> Vector2:
	var parent_ci := get_parent() as CanvasItem
	if parent_ci == null:
		return Vector2.ZERO
	var center_local := circle_widget.size * 0.5
	var center_canvas := circle_widget.get_global_transform_with_canvas() * center_local
	return parent_ci.get_global_transform_with_canvas().affine_inverse() * center_canvas

func _toggle_properties() -> void:
	properies_container.visible = !properies_container.visible
	update_widget()


signal moving
func _on_circle_widget_gui_input(event: InputEvent) -> void:
	# Generated by GitHub Copilot (GPT-5.3-Codex): drag widget by the circle handle.
	if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT:
		if event.pressed:
			_is_dragging = true
			_drag_offset = position - _parent_local_mouse_pos()
			accept_event()
		else:
			_is_dragging = false
			accept_event()

	if event is InputEventMouseMotion and _is_dragging:
		position = _parent_local_mouse_pos() + _drag_offset
		_update_coords_from_position()
		accept_event()
		moving.emit()

func _parent_local_mouse_pos() -> Vector2:
	var parent_ci := get_parent() as CanvasItem
	if parent_ci == null:
		return Vector2.ZERO
	var mouse_canvas := get_viewport().get_mouse_position()
	return parent_ci.get_global_transform_with_canvas().affine_inverse() * mouse_canvas

func _update_coords_from_position() -> void:
	coords = _circle_center_in_parent_local()

func update_position_from_coords() -> void:
	position += coords - _circle_center_in_parent_local()

func update_widget() -> void:
	await get_tree().process_frame
	update_position_from_coords()
	changed.emit()

signal closed
func _on_close_button_pressed() -> void:
	closed.emit()
	update_widget()
	queue_free()

func _on_h_slider_value_changed(value: float) -> void:
	update_widget()
func _on_pov_image_rect_item_rect_changed() -> void:
	pass#update_widget()
func _on_top_pov_name_text_changed(new_text: String) -> void:
	update_widget()
func _on_left_pov_name_text_changed(new_text: String) -> void:
	update_widget()
func _on_right_pov_name_text_changed(new_text: String) -> void:
	update_widget()
func _on_bottom_pov_name_text_changed(new_text: String) -> void:
	update_widget()
func _on_pov_directions_stack_widget_changed() -> void:
	update_widget()
func _on_stack_widget_changed() -> void:
	update_widget()
